variable "var_azure_region" {}
variable "aks_resource_group_name" {}
variable "oms_resource_group_name" {}
variable "network_resource_group_name" {}
variable "network_security_group" {}
variable "virtual_network_name" {}
variable "virtual_subnet_name" {}
variable "oms_name" {}
variable "aks_name" {}
variable "network_security_group_name" {}
variable "aks_cluster_name" {}
variable "tags" {}